apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: PGID
              value: "{{ .Values.PGID }}"
            - name: PUID
              value: "{{ .Values.PUID }}"
            - name: TZ
              value: "{{ .Values.TZ }}"
          image: lscr.io/linuxserver/transmission:latest
          name: transmission
          ports:
            - containerPort: 9091
              hostPort: 9091
              protocol: TCP
            - containerPort: 51413
              hostPort: 51413
              protocol: TCP
            - containerPort: 51413
              hostPort: 51413
              protocol: UDP
          volumeMounts:
            {{- range .Values.transmission.volumes }}
              - mountPath: {{ .mountPath }}
                name: {{ .volName }}
            {{- end }}    
      restartPolicy: Always
      volumes:
        {{- range .Values.transmission.volumes }}
        - name: {{ .volName }}
          persistentVolumeClaim:
            claimName: pvc-{{ .volName }}
        {{- end }}
