{{- range .Values.transmission.volumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .volName }}
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .storage }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ $.Values.hostname }}
{{- end }}
