apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pvc-watch
  name: pvc-watch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
