apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: local
  name: pvc-downloads
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
