apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/transmission-default: "true"
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: HOST_WHITELIST
            - name: PASS
            - name: PEERPORT
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/transmission:latest
          name: transmission
          ports:
            - containerPort: 9091
              hostPort: 9091
              protocol: TCP
            - containerPort: 51413
              hostPort: 51413
              protocol: TCP
            - containerPort: 51413
              hostPort: 51413
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: pvc-config
            - mountPath: /downloads
              name: pvc-downloads
            - mountPath: /watch
              name: pvc-watch
      restartPolicy: Always
      volumes:
        - name: pvc-config
          persistentVolumeClaim:
            claimName: pvc-config
        - name: pvc-downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: pvc-watch
          persistentVolumeClaim:
            claimName: pvc-watch
