apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wireguard
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/vpn-default: "true"
        io.kompose.service: wireguard
    spec:
      containers:
        - env:
            - name: ALLOWEDIPS
              value: 0.0.0.0/0
            - name: INTERNAL_SUBNET
              value: 10.13.13.0
            - name: LOG_CONFS
              value: "true"
            - name: PEERDNS
              value: auto
            - name: PEERS
              value: "1"
            - name: PERSISTENTKEEPALIVE_PEERS
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SERVERPORT
              value: "51820"
            - name: SERVERURL
              value: wireguard.domain.com
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/wireguard:latest
          name: wireguard
          ports:
            - containerPort: 51820
              hostPort: 51820
              protocol: UDP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /config
              name: wireguard-claim0
            - mountPath: /lib/modules
              name: wireguard-claim1
      restartPolicy: Always
      volumes:
        - name: wireguard-claim0
          persistentVolumeClaim:
            claimName: wireguard-claim0
        - name: wireguard-claim1
          persistentVolumeClaim:
            claimName: wireguard-claim1
