apiVersion: v1
kind: Pod
metadata:
  name: vscodium
spec:
  containers:
  - name: vscodium
    image: lscr.io/linuxserver/vscodium:latest
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
    ports:
      - name: web
        containerPort: 3000
        protocol: TCP
      - name: web2
        containerPort: 3001
        protocol: TCP
